# Site settings
newContentEditor = ""
baseURL = "http://chawkinsuf.com/"
languageCode = "en-us"
title = "Sea Hawk Photography"
theme = "forty"
disableKinds = ["section"]

cleanDestinationDir = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[taxonomies]

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  imageBaseUrlProduction = "http://127.0.0.1:1313"
  imageBaseUrlDevelopment = "http://127.0.0.1:1314"

  # Provide your metadata here.
  name = "Chris Hawkins"
  description = "Take a look at my pretty photos"

  # Link custom assets relative to /static
  custom_css = ["js/photoswipe/photoswipe.css", "js/photoswipe/default-skin/default-skin.css", "css/grid.css"]
  custom_js  = ["js/photoswipe/photoswipe.js", "js/photoswipe/photoswipe-ui-default.js", "js/gallery.js", "js/isotope/isotope.pkgd.min.js"]
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Sea Hawk Photography"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

#    [[params.navigation.links]]
#      name = "Galleries"
#      url = "galleries"

#    [[params.navigation.links]]
#      name = "Elements"
#      url = "elements.html"

#    # Button Style 1
#    [[params.navigation.button1]]
#      name = "See Photos"
#      url = "galleries"

#    # Button Style 2
#    [[params.navigation.button2]]
#      name = "Log In"
#      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Pictures from a place"
    subtitle = "Lot's of different stuff to see. Only my best work goes here."
    buttonText = "See Photos"


  # Tiles Section
  [params.tiles]
    enable = true

    [[params.tiles.showcase]]
      title = "Nature"
      subtitle = "Look at all the furry animals"
      image = "nature-showcase.jpg"
      url = "galleries/nature"

    [[params.tiles.showcase]]
      title = "Portraits"
      subtitle = "Pictures of people"
      image = "portraits-showcase.jpg"
      url = "galleries/portraits"

    [[params.tiles.showcase]]
      title = "Sports"
      subtitle = "Action shots"
      image = "sports-showcase.jpg"
      url = "galleries/sports"

    [[params.tiles.showcase]]
      title = "Vehicles"
      subtitle = "Planes, trains and automobiles"
      image = "vehicles-showcase.jpg"
      url = "galleries/vehicles"

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "See Photos"
    url = "galleries"


  # Contact section
  [params.contact]
    enable = false
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "example@domain.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Chris Hawkins"
